(function(z){
z.nu=function(a){return function(){var b=this||z.t,b=b.closure_memoize_cache_||(b.closure_memoize_cache_={}),c,d=z.ka(a);c=arguments;for(var d=[d],f=c.length-1;0<=f;--f)d.push(typeof c[f],c[f]);c=d.join("\x0B");return b.hasOwnProperty(c)?b[c]:b[c]=a.apply(this,arguments)}};var ou=function(a){z.Tl.call(this,"register");this.Kt=a};var pu=function(){z.S.call(this)};
var qu=function(){function a(){(0,window.$)(this).trigger("requestStory")}function b(){var a=f.filter(".current");a.length&&d.css("top",a.position().top+a.height()/2-10)}var c={member:z.nu(function(a){return window.$.get("/node/HomeHeroStoryV2",{params:{member_hash:a}})}),topic:z.nu(function(a){return window.$.get("/node/HomeTopicStoryV2",{params:{url_token:a}})})},d=(0,window.$)("div.single-story \x3e .icon-sign").addClass("visible"),f=(0,window.$)("a.rep"),g=null;f.mouseenter(function(){g=(0,window.setTimeout)((0,z.r)(a,
this),500)}).mouseleave(function(){(0,window.clearTimeout)(g)}).click(a).on("requestStory",function(){var a=(0,window.$)(this),f=a.data(),g=f.type,f=f.token;a.addClass("current").siblings().removeClass("current");b();c[g](f).done(function(b){(0,window.$)(".single-story-inner").fadeOut(150,function(){(0,window.$)(this).remove();(0,window.$)(b).insertAfter(d).hide().fadeIn(150)});a.trigger("afterRequestStory")})});b()};
var ru=function(){function a(){(0,window.clearInterval)(g);g=null}function b(){g||(g=(0,window.setInterval)(function(){(0,window.$)(c()).trigger("requestStory")},5E3))}function c(){var a=f.filter(":not(.current)").get();z.y.OT(a);return a[0]}var d=(0,window.$)("div.single-story"),f=(0,window.$)("div.rep"),g=null;d.hover(a,b);f.on("requestStory",a).on("afterRequestStory",b);return{start:b,stop:a}};
var su=function(a){function b(){c.hide();d.show()}var c=(0,window.$)("div.mobi-front"),d=(0,window.$)("div.desk-front");c.on("click",".js-signin, .js-signup",function(a){d.find(".js-title-label").text("\u8fd4\u56de");d.find(".return").off().click(function(){window.location.hash=""});b();(0,window.$)(a.target).hasClass("js-signin")?window.location.hash="signin":window.location.hash="signup"});a.v().g(window,"hashchange",function(){var a=window.location.hash.slice(1);"signin"===a?(b(),tu(this)):"signup"===
a?(b(),this.Wm.hide(),this.Cc.show(),this.Wh()):(d.css("display",""),c.css("display",""))});a.v().g(z.X,["accountcallback","sina_callback","qqconn_callback"],b);var f=window.location.hash.slice(1);"signin"!==f&&"signup"!==f||b();uu(a);vu(a);a.no();wu();a.Wh();(0,window.$)(".view-signin .js-signup").click(function(){a.Wm.hide();a.Cc.show();a.Wh()});(0,window.$)(".view-signup .js-signin").click(function(){tu(a)});(0,window.$)(".js-bindweibo").click(function(){z.pk("sina")});(0,window.$)(".js-bindqq").click(function(){z.pk("qq")});
(0,window.$)(".js-bindwechat").click(function(){z.pk("wechat")})};var uu=function(a){a.Wm=(0,window.$)(".view-signin");var b=(0,window.$)("form",a.Wm),c=(0,window.$)("button.submit",b);b.validate(window.$.extend({},a.wJ,{submitHandler:z.ck(c,window.$.proxy(a.qz,a))}));c=(0,window.$)(".captcha-wrap",b).get(0);a.Qy=new z.rk;a.Qy.w(c);z.sk(a.Qy);var d=(0,window.$)('input[name\x3d"account"]',b);(0,window.$)(".unable-login",a.Wm).click(function(){(new z.cm(d.val())).F(!0)})};
var vu=function(a){a.Cc=(0,window.$)(".view-signup");var b=(0,window.$)("form",a.Cc),c=(0,window.$)("button.submit",b);b.validate(window.$.extend({},a.wJ,{submitHandler:z.ck(c,window.$.proxy(a.Zj,a))}));var d=(0,window.$)('input[name\x3d"account"]',b);a.Cc.on("click",".switch-to-login",function(){tu(a);var b=d.val();b&&(0,window.$)('input[name\x3d"account"]',a.cV).val(b)});c=(0,window.$)(".captcha-wrap",b).get(0);a.Jt=new z.rk;a.Jt.w(c);z.sk(a.Jt);a.Ef=z.qk(b);a.hy()};
var tu=function(a){a.Cc.hide();a.Wm.show();a.Wh()};var wu=function(){var a=z.bk.get("accountcallback");z.bk.remove("accountcallback");if(a){a=(0,window.decodeURIComponent)(a);try{var b=JSON.parse(a);z.X.dispatchEvent(new z.nk("accountcallback",b))}catch(c){}}};z.v(ou,z.$l);ou.prototype.B=function(){ou.o.B.call(this);this.ha(xu)};ou.prototype.D=function(){ou.o.D.call(this);this.Fb()};
ou.prototype.Fb=function(){var a=(0,window.$)("form",this.lb);this.Fe(a,this.Zj);(0,window.$)('input[name\x3d"phone_num"]',a).val(this.Kt.phone_num);var b=(0,window.$)(".send-code",a),c=(0,window.$)('input[name\x3d"phone_num"]',a);z.bm(this,b,function(){var b=c.val(),f=this;window.$.get("/send_register_verification_code/sms",window.$.param({phone_num:b}),function(b){b.r&&(b=b.data,f.pb(b,"account","phone_num"),a.data("validator").showErrors(b))})})};
ou.prototype.Zj=function(a){var b=this,c=(0,window.$)(a);a=window.$.extend({},this.Kt,c.hg());return window.$.post("/register/phone_num",a,function(a){a.r?(a=a.data,b.pb(a,"account","phone_num"),c.data("validator").showErrors(a)):b.Xc()})};var xu='\x3cdiv class\x3d"title verification"\x3e\x3ch1\x3e\u9a8c\u8bc1\u624b\u673a\x3c/h1\x3e\x3ch2\x3e\u8bf7\u8f93\u5165\u4f60\u6536\u5230\u7684 6 \u4f4d\u6570\u77ed\u4fe1\u9a8c\u8bc1\u7801\x3c/h2\x3e\x3c/div\x3e\x3cdiv class\x3d"view verification"\x3e\x3cform\x3e\x3cdiv class\x3d"input-wrapper"\x3e\x3cinput type\x3d"text" name\x3d"phone_num" placeholder\x3d"\u624b\u673a\u53f7" required\x3e\x3c/div\x3e\x3cdiv class\x3d"input-wrapper verification-code"\x3e\x3cinput type\x3d"text" name\x3d"verification_code" placeholder\x3d"6 \u4f4d\u6570\u9a8c\u8bc1\u7801" maxlength\x3d"6" required\x3e\x3cbutton type\x3d"button" class\x3d"send-code"\x3e\u91cd\u53d1\u9a8c\u8bc1\u7801\x3c/button\x3e\x3c/div\x3e\x3cbutton class\x3d"submit blue-button"\x3e\u8fdb\u5165\u77e5\u4e4e\x3c/button\x3e\x3c/form\x3e\x3c/div\x3e';z.v(pu,z.S);z.e=pu.prototype;z.e.init=function(){this.w(window.document.body)};z.e.D=function(a){pu.o.D.call(this,a);qu();su(this);this.to();z.Ei||(a=ru(),a.start(),z.hc(this,a.stop))};
z.e.to=function(){window.$.each({".app-link.ios":["click_zhihu_ios_dl_link","homepage_not_logged_in"],".app-link.android":["click_zhihu_android_dl_link","homepage_not_logged_in"],'a.app-download-button[href^\x3d"http://itunes"]':["click_zhihu_ios_dl_link","homepage_mobile_big_not_logged_in"],'a.app-download-button[href^\x3d"https://play.google.com"]':["click_zhihu_android_dl_link","homepage_mobile_big_not_logged_in"]},function(a,b){(0,window.$)(a).on("click",function(){z.W.apply(null,["app-promotion"].concat(b))})})};
z.e.hy=function(){var a=(0,window.$)('input[name\x3d"account"]',this.Cc).get(0);new z.Rl(a,{eh:a.parentNode})};z.e.qz=function(a){var b=(0,window.$)(a);a=b.hg();var c=this.Ie(a.account),d=c?"/login/email":"/login/phone_num";c?a.email=a.account:a.phone_num=a.account;delete a.account;var f=this;return window.$.post(d,a,function(a){a.r?(b.data("validator").showErrors(a.data),z.sk(f.Qy)):f.Xc()})};
z.e.Zj=function(a){a=(0,window.$)(a);var b=a.hg(),c=this.Ie(b.account),d=c?"/register/email":"/register/phone_num/validation";c?b.email=b.account:b.phone_num=b.account;delete b.account;b.userInfo=JSON.stringify(this.Ef);a.off(".recording");var f=this,g=a.data("validator");return c?window.$.post(d,b,function(a){a&&a.r?(z.sk(f.Jt),g.showErrors(a.data)):f.Xc()}):window.$.post(d,b,function(a){a.r?(z.sk(f.Jt),g.showErrors(a.data)):((new ou(b)).F(!0),window.$.get("/send_register_verification_code/sms",
{phone_num:b.phone_num}))})};z.e.Wh=function(){var a=this;z.Ll||(0,window.setTimeout)(function(){(0,window.$)("input[placeholder]:visible",a.lb).placeholder()},10)};
z.e.wJ={onkeyup:!1,onfocusout:!1,validClass:"",focusInvalid:!1,highlight:z.m,messages:{fullname:{required:"\u8bf7\u586b\u5199\u59d3\u540d"},account:{required:"\u8bf7\u586b\u5199\u624b\u673a\u53f7\u6216\u90ae\u7bb1"},password:{required:"\u8bf7\u586b\u5199\u5bc6\u7801"},captcha:{required:"\u8bf7\u586b\u5199\u9a8c\u8bc1\u7801"}},showErrors:function(a,b){if(b.length){b.sort(function(a,b){var c=["fullname","account","password","captcha"],d=z.y.indexOf(c,a.element.name),c=z.y.indexOf(c,b.element.name);
return d>c});var c=(0,window.$)(".failure",this.currentForm).show(),d=(0,window.$)(".failure ul",this.currentForm).empty();window.$.each(b,function(a,b){var h=(0,window.$)(b.element),l=(0,window.$)('\x3cli\x3e\x3ci class\x3d"icon-sign icon-sign-error"\x3e\x3c/i\x3e'+b.message+"\x3c/li\x3e").appendTo(d),n=(0,window.$)('\x3cspan class\x3d"switch-to-login"\x3e \u00b7 \u76f4\u63a5\u767b\u5f55\x3c/span\x3e');"\u8be5\u90ae\u7bb1\u5df2\u6ce8\u518c"===b.message||"\u8be5\u624b\u673a\u53f7\u5df2\u6ce8\u518c"===
b.message?n.appendTo(l):l.click(function(){h.focus()});h.one("focus",function(){l.remove();d.is(":empty")&&c.hide()})})}}};z.e.no=function(){this.v().g(z.X,"accountcallback",window.$.proxy(this.uQ,this))};z.e.uQ=function(a){a=a.vf;1===a.login?this.Xc():(new z.gm(a)).F(!0)};z.e.Ie=function(a){return!/^\+?[0-9]+$/.test(a)};z.e.Xc=function(){var a=(new z.Sk(window.location.href)).Bd().get("next");a?window.location.href=a:window.location.reload()};z.ta("ZH.entrySignPage",function(){(new pu).init()});
z.rg("sign");}).call(this, __z_z__);
//@ sourceURL=module_sign.js