;(function () {var DUP_OPEN="BAIDU_DUP3",DUP_TM="BAIDU_DUP2_SETJSONADSLOT",VERSION_NUMBER="1430990801",require=window[DUP_OPEN+"_require"],define=window[DUP_OPEN+"_define"],POS_URL="http://pos.baidu.com/ecom?";
define&&define("union/common/bom1430990801",[],function(){var i={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(i.ie=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(i.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(i.firefox=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(i.safari=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(i.chrome=+RegExp.$1);
try{/(\d+\.\d)/.test(window.external.max_version)&&(i.maxthon=+RegExp.$1)}catch(g){}i.isWebkit=/webkit/i.test(navigator.userAgent);i.isGecko=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);i.isStrict="CSS1Compat"==document.compatMode;return{browser:i,canFixed:function(){var c=!0;if(this.browser.ie&&(7>this.browser.ie||"BackCompat"===document.compatMode))c=!1;return c},getScrollWidth:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.scrollWidth:
c.document.documentElement.scrollWidth}catch(h){return 0}},getScrollHeight:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.scrollHeight:c.document.documentElement.scrollHeight}catch(h){return 0}},getClientWidth:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.clientWidth:c.document.documentElement.clientWidth}catch(h){return 0}},getClientHeight:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.clientHeight:
c.document.documentElement.clientHeight}catch(h){return 0}},getScrollTop:function(c){c=(c||window).document;return window.pageYOffset||c.documentElement.scrollTop||c.body.scrollTop},getScrollLeft:function(c){c=(c||window).document;return window.pageXOffset||c.documentElement.scrollLeft||c.body.scrollLeft},isWindow:function(c){var h=!1;try{c&&"object"===typeof c&&c.document&&"setInterval"in c&&(h=!0)}catch(b){h=!1}return h},isInIframe:function(c){c=c||window;return c!=window.top&&c!=c.parent||!this.isWindow(c)},
isInCrossDomainIframe:function(c,h){for(var h=2===arguments.length?h:c.parent,b=0;10>b++&&this.isInIframe(c,h);){var f;try{f=!!c.parent.location.toString()}catch(e){f=!1}if(!f)return!0;c=c.parent}return 10<=b?!0:!1},sendRequestViaImage:function(c,h){var b=new Image,f="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),h=h||window;h[f]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=null;b=h[f]=null};b.src=c},getDocument:function(c){if(!c)return document;"string"===
typeof c&&(c=document.getElementById(c));return 9===c.nodeType?c:c.ownerDocument||c.document},getWindow:function(c){"string"===typeof c&&(c=document.getElementById(c));c=this.getDocument(c);return c.parentWindow||c.defaultView||null},getTopWindow:function(c){c=c||window;return this.isInIframe(c)&&!this.isInCrossDomainIframe(c,c.top)&&this.isWindow(c.top)?c.top:c}}});
define&&define("union/common/cookie1430990801",[],function(){return{getRaw:function(i,g){var c,h=RegExp("(^| )"+i+"=([^;]*)(;|$)").exec((g||window).document.cookie);h&&(c=h[2]);return c},setRaw:function(i,g,c){var c=c||{},h=c.expires;"number"==typeof c.expires&&(h=new Date,h.setTime(h.getTime()+c.expires));document.cookie=""+i+"="+g+(c.path?"; path="+c.path:"")+(h?"; expires="+h.toGMTString():"")+(c.domain?"; domain="+c.domain:"")+(c.secure?"; secure":"")},remove:function(i){var g=new Date;g.setTime(g.getTime()-
86400);this.setRaw(i,"",{path:"/",expires:g})}}});
define&&define("union/common/dom1430990801",["union/common/oo1430990801","union/common/bom1430990801"],function(i,g){return i(function(c){var h=g.browser;return{g:function(b,c){return"string"===typeof b||b instanceof String?(c||window).document.getElementById(b):b},is:function(b,f){var e=!0;if("string"===typeof f)return b.id===f;if(f.constructor===Object)return c.each(f,function(c,d){var f=(b.getAttribute?b.getAttribute(d):b[d])||b[d];if("tagName"===d){if(f.toUpperCase()!=c.toUpperCase())return e=
!1}else if(f!=c)return e=!1}),e;if(f.constructor===Array){var d=f.concat([]);d.reverse();for(var j=b;j&&d.length;j=j.parentNode)this.is(j,d[0])&&d.shift();return!d.length?!0:!1}},traverse:function(b,c){if(b&&!1!==c(b)){var e=b.childNodes;if(e)for(var d=0,j=e.length;d<j;d++)if(!1===this.traverse(e[d],c))return!1}},subOne:function(b,c){var e=this;b.constructor===Object&&(b=this.one(b));if("string"===typeof c){for(var d=document.getElementById(c),j=d;j;){if(j===b)return d;j=j.parentNode}return null}if(c.constructor===
Object){var h=null;e.traverse(b,function(b){if(e.is(b,c))return h=b,!1});return h}},one:function(b){if(b){if(b.nodeName)return b;1<arguments.length&&(b=Array.prototype.slice.call(arguments,0));if("string"===typeof b)return document.getElementById(b);if(b.constructor===Object)return this.subOne(document.documentElement,b);if(b.constructor===Array){for(var c=b.concat([]),e=document.documentElement;c.length&&e;)e=this.subOne(e,c.shift());return e}}},ready:function(b,f,e){var e=e||this.win||window,d=
e.document;this.domReadyMonitorRunTimes=0;this.readyFuncArray=this.readyFuncArray||[];this.readyFuncArray.push({func:b,delay:f||0,done:!1});var j=c.proxy(function(){var b=!1;this.domReadyMonitorRunTimes++;var c=!1;try{e.frameElement&&(c=!0)}catch(f){c=!0}if(h.ie&&9>h.ie&&!c)try{d.documentElement.doScroll("left"),b=!0}catch(j){}else if("complete"===d.readyState||this.domContentLoaded)b=!0;else if(3E5<this.domReadyMonitorRunTimes){this.domReadyMonitorId&&(e.clearInterval(this.domReadyMonitorId),this.domReadyMonitorId=
null);return}if(b)try{if(this.readyFuncArray&&this.readyFuncArray.length)for(var b=0,i=this.readyFuncArray.length;b<i;b++){var g=this.readyFuncArray[b];g&&g.func&&!g.done&&(g.delay?(g.done=!0,e.setTimeout(g.func,g.delay)):(g.done=!0,g.func()))}}catch(u){throw u;}finally{this.domReadyMonitorId&&(e.clearInterval(this.domReadyMonitorId),this.domReadyMonitorId=null)}},this),b=c.proxy(function(){this.domContentLoaded=!0;j()},this);this.domReadyMonitorId||(this.domReadyMonitorId=e.setInterval(j,50),d.addEventListener?
(d.addEventListener("DOMContentLoaded",b,!1),e.addEventListener("load",b,!1)):d.attachEvent&&e.attachEvent("onload",b,!1))},canFixed:function(){var b=!0;if(h.ie&&(7>h.ie||"BackCompat"===document.compatMode))b=!1;return b},bind:function(b,c,e){"string"===typeof b&&(b=this.one(b));c=c.replace(/^on/i,"").toLowerCase();b.addEventListener?b.addEventListener(c,e,!1):b.attachEvent&&b.attachEvent("on"+c,e);return b},unbind:function(b,c,e){b=this.one(b);if(!b)return null;c=c.replace(/^on/i,"").toLowerCase();
b.removeEventListener?b.removeEventListener(c,e,!1):b.detachEvent&&b.detachEvent("on"+c,e);return b},getStyle:function(b,c){var e;"string"===typeof b&&(b=this.one(b));var d=g.getDocument(b),j="",j=-1<c.indexOf("-")?c.replace(/[-_][^-_]{1}/g,function(b){return b.charAt(1).toUpperCase()}):c.replace(/[A-Z]{1}/g,function(b){return"-"+b.charAt(0).toLowerCase()});d&&d.defaultView&&d.defaultView.getComputedStyle?((d=d.defaultView.getComputedStyle(b,null))&&(e=d.getPropertyValue(c)),"boolean"!==typeof e&&
!e&&(e=d.getPropertyValue(j))):b.currentStyle&&((d=b.currentStyle)&&(e=d[c]),"boolean"!==typeof e&&!e&&(e=d[j]));return e},getPosition:function(b,c){c=c||window;"string"===typeof b&&(b=this.one(b));if(b){for(var e=this.getPositionCore(b),d,j=0;c!=c.parent&&10>j;)j++,d=this.getPositionCore(c.frameElement),e.left+=d.left,e.top+=d.top,c=c.parent;return e}},getPositionCore:function(b){"string"===typeof b&&(b=this.one(b));var c=g.getDocument(b),e=g.browser;0<e.isGecko&&c.getBoxObjectFor&&this.getStyle(b,
"position");var d={left:0,top:0},j;if(b==(e.ie&&!e.isStrict?c.body:c.documentElement)||!b)return d;if(b.getBoundingClientRect)b=b.getBoundingClientRect(),d.left=Math.floor(b.left)+Math.max(c.documentElement.scrollLeft,c.body.scrollLeft),d.top=Math.floor(b.top)+Math.max(c.documentElement.scrollTop,c.body.scrollTop),d.left-=c.documentElement.clientLeft,d.top-=c.documentElement.clientTop,b=c.body,c=parseInt(this.getStyle(b,"borderLeftWidth"),10),b=parseInt(this.getStyle(b,"borderTopWidth"),10),e.ie&&
!e.isStrict&&(d.left-=isNaN(c)?2:c,d.top-=isNaN(b)?2:b);else{j=b;do{d.left+=j.offsetLeft;d.top+=j.offsetTop;if(0<e.isWebkit&&"fixed"==this.getStyle(j,"position")){d.left+=c.body.scrollLeft;d.top+=c.body.scrollTop;break}j=j.offsetParent}while(j&&j!=b);if(0<e.opera||0<e.isWebkit&&"absolute"==this.getStyle(b,"position"))d.top-=c.body.offsetTop;for(j=b.offsetParent;j&&j!=c.body;){d.left-=j.scrollLeft;if(!e.opera||"TR"!=j.tagName)d.top-=j.scrollTop;j=j.offsetParent}}return d},getOuterWidth:function(c,
f){var c=this.one(c),e=c.offsetWidth;if(f)var d=this.getStyle(c,"marginLeft").toString().toLowerCase().replace("px","").replace("auto","0"),j=this.getStyle(c,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),e=e+(parseInt(d||0,10)+parseInt(j||0,10));return e},getOuterHeight:function(c,f){var c=this.one(c),e=c.offsetHeight;if(f)var d=this.getStyle(c,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),j=this.getStyle(c,"marginBottom").toString().toLowerCase().replace("px",
"").replace("auto","0"),e=e+(parseInt(d||0,10)+parseInt(j||0,10));return e},getTopIframe:function(c){var c=this.one(c),f=this.getWindow(c),e=0;if(this.isInIframe(window)&&!g.isInCrossDomainIframe(window)){for(;f.parent!=window.top&&10>e;)e++,f=f.parent;10>e&&(c=f.frameElement||c)}return c},getOpacityInWin:function(c){var f=this.one(c),c=this.getWindow(f),e=100,d;try{for(;f&&f.tagName;){d=100;if(this.browser.ie){if(5<this.browser.ie)try{d=f.filters.alpha.opacity||100}catch(j){}e=e>d?d:e}else{try{d=
100*(c.getComputedStyle(f,null).opacity||1)}catch(h){}e*=d/100}f=f.parentNode}}catch(i){}return e||100},getOpacity:function(c){for(var f=this.one(c),c=this.getWindow(f),f=this.getOpacityInWin(f),e=100,d=0;this.isInIframe(c);){d++;if(g.isInCrossDomainIframe(c,c.parent))break;else e=100,c.frameElement&&(e=this.getOpacityInWin(c.frameElement)),f*=e/100;c=c.parent}return f}}})});
define&&define("union/common/logic1430990801",[],function(){return{escapeToEncode:function(i){(i=i||"")&&(i=i.replace(/%u[\d|\w]{4}/g,function(i){return encodeURIComponent(unescape(i))}));return i},template:function(i,g){return i.replace(/{(.*?)}/g,function(c,h){return g[h]||""})},jsonToObj:function(i){var g="";window.JSON&&window.JSON.parse&&(g=window.JSON.parse(i));return g},getUrlQueryValue:function(i,g){if(i&&g){var c=i.match(RegExp("(^|&|\\?|#)"+g+"=([^&]*)(&|$)",""));if(c)return c[2]}return null},
parseUrlQuery:function(i,g){var i=i||"",g=g||"?",c=arguments.callee;c.hasOwnProperty[g]||(c[g]={});c=c[g];if(c.hasOwnProperty(i))return c[i];var h={},b=i.indexOf(g),f=i.substring(b+1).split("&");if(-1!==b)for(var b=0,e=f.length;b<e;b++){var d=f[b].split("="),j=decodeURIComponent(d[0]),d=decodeURIComponent(d[1]);h.hasOwnProperty(j)?(h[j].constructor!==Array&&(h[j]=[h[j]]),h[j].push(d)):h[j]=d}return c[i]=h}}});
define&&define("union/common/oo1430990801",[],function(){function i(c,f){if(c.constructor===Array)for(var e=0,d=c.length;e<d;e++){if(!1===f.call(c,c[e],e,c))return!1}else{var e=!{toString:1}.propertyIsEnumerable("toString"),j="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(d in c)if(c.hasOwnProperty(d)&&!1===f.call(c,c[d],d,c))return!1;if(e){e=0;for(d=j.length;e<d;e++){var h=j[e];if(c.hasOwnProperty(h)&&!1===f.call(c,h,e,c))return!1}}}return!0}
function g(c,f,e){i(f,function(d,f){if(!c.hasOwnProperty(f)||e)c[f]=d})}function c(c){function f(){}if(Object.create)return Object.create(c);f.prototype=c;return new f}var h=function(c){var f=h.create(h);return c.call(f,f,f.X)};h.X={};h.create=c;h.each=i;h.$class=function(c,f){var e=c.hasOwnProperty("constructor")?c.constructor:function(){};e.prototype=c;e.prototype.constructor=e;f=f||{};f.statics&&g(e,f.statics);return e};h.extend=function(b,f,e){var d;d=f.hasOwnProperty("constructor")?f.constructor:
function(){b.constructor.apply(this,arguments)};d.prototype=c(b.prototype);g(d.prototype,f,!0);d.prototype.constructor=d;d.prototype.$super=b.prototype;d.prototype.$Super=b;g(d,b);e=e||{};e.statics&&g(d,e.statics,!0);return d};h.namespace=function(c){var c=c.split("."),f=this.X;i(c,function(c){f.hasOwnProperty(c)||(f[c]={});f=f[c]});return f};h.proxy=function(c,f,e){return function(){e=e||[];for(var d=0,j=arguments.length;d<j;d++)e.push(arguments[d]);return c.apply(f||{},e)}};return h});
define&&define("union/business/businessLogic1430990801",["union/preview1430990801","union/common/dom1430990801","api"],function(i,g,c){var h={inlay:8,"float":2,patch:2,linkunit:20,popup:1},b={inlay:{},"float":{},patch:{},linkunit:{},popup:{}},f={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};
return{processSlotData:function(e){var d=e._html||{},b="",f=d.conW||0,h=d.conH||0,g=POS_URL,q=e.id.split("_")[0],f=parseInt(f,10)||parseInt(e._w,10)||parseInt(e.sw,10)||parseInt(d.rsi0,10),h=parseInt(h,10)||parseInt(e._h,10)||parseInt(e.sh,10)||parseInt(d.rsi1,10),x=e.displayType,w=d.tn||"",u=w.toLowerCase(),s=d.ch||0,t=e.qn||"",A=d.n||"",m=d.dai||0;d.dtm=DUP_TM;d.dc="2";d.di=q;d.ti=c.getDocumentTitle();(e=c.getInfo("timestampWathcer"+e.id))&&(d.tt=e.t1+"."+(e.t2-e.t1)+"."+(e.t3-e.t1)+"."+(+new Date-
e.t1));var e=[],p;for(p in d)p&&d.hasOwnProperty(p)&&e.push(""+p+"="+encodeURIComponent(d[p].toString()));b=e.join("&");if((p=i.getPreviewUrlData(d,x))&&void 0!==p.serviceUrl&&void 0!==p.paramString)g=p.serviceUrl,b=p.paramString;return{slotId:q,slotWidth:f,slotHeight:h,displayType:x,styleType:u,iframeId:"cproIframe_"+q+"_"+d.dai,unionAccount:A,adIndex:m,channel:s,pvId:t,stuffType:"unknown",serviceUrl:g,paramString:b,delayIn:d.delayIn,delayOut:d.delayOut,sessionSync:!1!==d.sessionSync&&"false"!==
d.sessionSync,closeFor:d.closeFor,xuantingType:d.xuanting,tn:w}},processAdsCountOption:function(c){var d={};d.deviceType=(c.deviceType||"pc").toLowerCase();d.displayType=(c.displayType||"inlay-fixed").toLowerCase();d.styleType=(c.styleType||"template_inlay_all_normal").toLowerCase();d.stuffType=(c.stuffType||"text").toLowerCase();d.domId=c.domId;if(-1<d.styleType.indexOf("tlink")||-1<d.styleType.indexOf("linkunit"))d.displayType="linkunit-fixed";0<=d.styleType.indexOf("float_xuanfuwin")&&(d.displayType=
"popup-float");c=d.displayType.split("-");d.displayMainType=c[0]||"inlay";d.displaySubType=c[1]||"fixed";return d},checkAdsCount:function(c){var c=this.processAdsCountOption(c),d=c.displayMainType;return this.getAdsCount(c)<h[d]},getAdsCount:function(c){var c=this.processAdsCountOption(c),d=0,c=b[c.displayMainType],f;for(f in c)f&&c[f]&&c.hasOwnProperty(f)&&(g.g(f)?d++:c[f]=void 0);return d},setAdsCount:function(c){c=this.processAdsCountOption(c);b[c.displayMainType][c.domId]=1;return!0},getWrapper:function(c,
d){var b=document.getElementById("cpro_"+c);b||(b=document.getElementById(d));return b},getDisplayTypeByValue:function(c){return f[c]},setupViewWatch:function(c){var d=c.slotId;require(["viewWatch"],function(b){b.register({id:d,wrapperId:c.iframeId,logType:"block",extra:"ch="+c.channel+"&jk="+c.pvId+"&n="+c.unionAccount})},!0)}}});
define&&define("union/preview1430990801",["union/common/bom1430990801","union/common/logic1430990801","union/common/cookie1430990801"],function(i,g,c){function h(c){c=decodeURIComponent(c).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return g.jsonToObj(c)}function b(b,e){var d;d=e?e.substring(e.indexOf("?")):i.isInCrossDomainIframe(window)?window.location.search.slice(1):window.top.location.search.slice(1);var h=document.referrer,r=0<=b.indexOf("inlay")||
"ui"===b?"bd_cpro_prev":"bd_cpro_fprev",n="",o;try{o=document.cookie}catch(q){}-1!==d.indexOf(r)&&(n=g.getUrlQueryValue(d,r));!n&&o&&-1!==o.indexOf(r)&&(n=c.getRaw(r));!n&&-1!==h.indexOf(r)&&(n=g.getUrlQueryValue(h,r));return n}return{getPreviewUrlData:function(c,e){var d=window.location.href,j=parseInt(c.rsi0,10),i=parseInt(c.rsi1,10),g=parseInt(c.at,10),o=!1,q=b(e,d);if(q)if(q=h(q),void 0===g&&(g=1),1!==parseInt(q.type,10)&&2===(g&2))o=parseInt(q.imgWidth,10)===parseInt(j,10)&&parseInt(q.imgHeight,
10)===parseInt(i,10);else if(1===parseInt(q.type,10)&&(1===(g&1)||64===(g&64)||32===(g&32)))o=!0;return o?(j=0<=e.indexOf("inlay")||"ui"===e?"bd_cpro_prev":"bd_cpro_fprev",d=b(e,d),i=c.tn,g=h(d),o=null,0<=e.indexOf("inlay")?(g=parseInt(g.type,10),o={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===g?i+".html":2===g?"image.html":4===g?"flash.html":"blank_tips.html")+"?",paramString:(""+j+"=#"+d+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}):0<=e.indexOf("float")&&(g=parseInt(g.type,
10),g="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===g?"float_image.html":4===g?"float_flash.html":"blank_tips.html")+"?",j="tn="+i+("&"+j+"="+d).replace(/\./g,"%252e")+"&ut="+ +new Date,o={serviceUrl:g,paramString:j}),o):null}}});
define&&define("union/slide",["union/common/dom1430990801","union/business/businessLogic1430990801","union/common/bom1430990801"],function(i,g,c){function h(){return c.browser.ie&&7>c.browser.ie?!0:!1}function b(){return c.browser.ie&&7>c.browser.ie||c.browser.ie&&7==c.browser.ie&&"BackCompat"==document.compatMode?!1:!0}function f(c){c=c.curl||"";c=j(c);return c=d(c.urlhead,c.params)}function e(c,a){var a=a||{},l={};l.sid=a.sid||c.qn;l.tu=a.tu||c.cpro_id;l.domain=a.domain||window.location.host;l.stid=
a.stid||("baiduTlinkInlay"==c.tn?42:41);return l}function d(c,a){var l=[],d;for(d in a)l.push(d+"="+a[d]);return c+"?"+l.join("&")}function j(c){var a={},l=c.indexOf("?");if(0>l)return a;for(var d=c.substr(l+1).split("&"),b=0;b<d.length;b++){var e=d[b].split("=");2==e.length&&(a[e[0]]=e[1])}return{urlhead:c.substr(0,l),params:a}}function r(c){var a=new Image,l="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[l]=a;a.onload=a.onerror=a.onabort=function(){a.onload=a.onerror=
a.onabort=null;a=window[l]=null};a.src=c}function n(c,a){var l;l="module="+c;for(var d in a)l+="&"+d+"="+a[d];r("http://eclick.baidu.com/preshow.jpg?"+l)}function o(){var b=this;this.isSlideEnable=function(){return b.slideInfo.enable};this.setUrl=function(){!1==b.iframeUrlDone&&(b.dialog.src=this.getUrl(),b.iframeUrlDone=!0)};this.resetBottomLoc=function(){"left"==b.slidePos||"right"==b.slidePos?b.outerDiv.style.top=c.getScrollTop()+c.getClientHeight()-b.verticalPos-b.outer_height+"px":"bottom"==
b.slidePos?b.outerDiv.style.top=c.getScrollTop()+c.getClientHeight()-b.verticalPos-b.slideDivHeight-b.slideInfo.total-b.slideInfo.move+"px":"top"==b.slidePos&&(b.outerDiv.style.top=c.getScrollTop()-b.verticalPos-b.outer_height+b.slideDivHeight+b.slideInfo.total+b.slideInfo.move+"px")};this.init=function(a){this.slide_cpro_id=a.cpro_id;if(!(void 0==a.curl||""==a.curl)){this.slideUrl=a.curl;var b=j(this.slideUrl);if(!(void 0==b.params.tn||0>b.params.tn.indexOf("baiduTlinkInlay")&&0>b.params.tn.indexOf("baiduCustSTagLinkUnit"))){this.slideWidth=
parseInt(""==b.params.rsi0||void 0==b.params.rsi0?"0":b.params.rsi0);this.slideHeight=parseInt(""==b.params.rsi1||void 0==b.params.rsi1?"0":b.params.rsi1);this.slidePos=void 0==a.cpro_slideLU_abs_pos?a.pos:a.cpro_slideLU_abs_pos;"left"!=this.slidePos&&"right"!=this.slidePos&&"bottom"!=this.slidePos&&"top"!=this.slidePos&&(this.slidePos="left");void 0==a.cpro_slideLU_rel_pos?(this.slideBottomPos=a.bpos,this.verticalPos=parseInt(""==a.ver||void 0==a.ver?"0":a.ver)):"left"==this.slidePos||"right"==this.slidePos?
(this.slideBottomPos="middle",this.verticalPos=parseInt(""==a.cpro_slideLU_rel_pos?"0":a.cpro_slideLU_rel_pos)):(this.slideBottomPos=a.cpro_slideLU_rel_pos,this.verticalPos=0);"left"!=this.slideBottomPos&&"right"!=this.slideBottomPos&&"middle"!=this.slideBottomPos&&(this.slideBottomPos="middle");if("bottom"==this.slidePos||"top"==this.slidePos)this.verticalPos=0;this.slidePercent=void 0==a.cpro_slideLU_out_per?parseFloat(""==a.per||void 0==a.per?"0":a.per):parseFloat(""==a.cpro_slideLU_out_per?"0":
a.cpro_slideLU_out_per);this.slideEndPercent=void 0==a.cpro_slideLU_in_per?parseFloat(""==a.per2||void 0==a.per2?"1":a.per2):parseFloat(""==a.cpro_slideLU_in_per?"0":a.cpro_slideLU_in_per);0.1>this.slideEndPercent-this.slidePercent&&(this.slideEndPercent=this.slidePercent+0.1);if(this.slidePercent>this.slideEndPercent||1<this.slideEndPercent)this.slideEndPercent=1;if(("bottom"==this.slidePos||"top"==this.slidePos)&&"rsi1"in b.params&&75<parseInt(b.params.rsi1))"hn"in b.params&&(a=b.params.hn,b.params.hn=
Math.floor(75*parseInt(b.params.hn)/parseInt(b.params.rsi1)),"adn"in b.params&&(b.params.adn=Math.floor(parseInt(b.params.adn)*parseInt(b.params.hn)/parseInt(a)),b.params.adn=Math.max(parseInt(b.params.adn),parseInt(b.params.hn)*parseInt(b.params.wn)))),this.slideHeight=b.params.rsi1=75;if(("left"==this.slidePos||"right"==this.slidePos)&&"rsi0"in b.params&&450<parseInt(b.params.rsi0))"wn"in b.params&&(a=b.params.wn,b.params.wn=Math.floor(450*parseInt(b.params.wn)/parseInt(b.params.rsi0)),"adn"in b.params&&
(b.params.adn=Math.floor(parseInt(b.params.adn)*parseInt(b.params.wn)/parseInt(a)),b.params.adn=Math.max(parseInt(b.params.adn),parseInt(b.params.hn)*parseInt(b.params.wn)))),this.slideWidth=b.params.rsi0=450;"stid"in b.params?"0"==b.params.stid?b.params.stid="14":"5"==b.params.stid&&(b.params.stid="15"):b.params.stid="14";this.slideUrl=d(b.urlhead,b.params);n("slide",{tu:this.slide_cpro_id,stid:b.params.stid,sid:b.params.qn||"",rsi0:this.slideWidth,rsi1:this.slideHeight,pos:this.slidePos,bpos:this.slideBottomPos,
per:this.slidePercent,per2:this.slideEndPercent,ver:this.verticalPos,random:+new Date});this.slideIsBarTitle=!0;this.iframeUrlDone=!1;this.scaleFactor=4.5;this.slideDivBtnBgSize=16;this.specSize=2;if("left"==this.slidePos||"right"==this.slidePos)102<=this.slideHeight?(this.slideDivWidth=30,this.slideBarTitleFontSize=16):89<=this.slideHeight?(this.slideDivWidth=26,this.slideBarTitleFontSize=14):76<=this.slideHeight?(this.specSize=0,this.slideDivWidth=22,this.slideBarTitleFontSize=12):(this.specSize=
0,this.slideDivWidth=22,this.slideBarTitleFontSize=12,this.slideIsBarTitle=!1),this.slideDivHeight=this.slideIsBarTitle?this.slideBarTitleFontSize*this.scaleFactor+this.slideDivWidth:this.slideDivWidth;else if("bottom"==this.slidePos||"top"==this.slidePos)this.slideDivHeight=30,this.slideBarTitleFontSize=16,this.slideDivWidth=this.slideIsBarTitle?this.slideBarTitleFontSize*this.scaleFactor+this.slideDivHeight:this.slideDivHeight;this.slideDivBgColor="#518CFF";this.iframeDivBorderWidth=1;this.iframeDivBorderColor=
"#518CFF";this.iframeBorderShadowSize=30;this.iframeBorderShadowSize>this.slideDivHeight&&(this.iframeBorderShadowSize=this.slideDivHeight);this.iframeBorderSpreadSize=5;if("top"==this.slidePos||"bottom"==this.slidePos)this.iframeDivBorderColor="#a2a2a2";if("left"==this.slidePos||"right"==this.slidePos)this.outer_width=this.slideWidth+2*this.iframeDivBorderWidth+this.slideDivWidth,this.outer_height=this.slideHeight+2*this.iframeDivBorderWidth;else if("bottom"==this.slidePos||"top"==this.slidePos)this.outer_width=
this.slideWidth+2*this.iframeDivBorderWidth+2*this.iframeBorderShadowSize,this.outer_height=this.slideHeight+2*this.iframeDivBorderWidth+this.slideDivHeight;this.slideInfo={};if("left"==this.slidePos||"right"==this.slidePos)this.slideInfo.total=this.slideWidth+2*this.iframeDivBorderWidth;else if("bottom"==this.slidePos||"top"==this.slidePos)this.slideInfo.total=this.slideHeight+2*this.iframeDivBorderWidth;this.slideInfo.move=-this.slideInfo.total;this.slideInfo.interval=this.slideInfo.total/6;this.slideInfo.speed=
50;this.slideInfo.enable=!0;this.outerDiv=document.createElement("div");b="width:"+this.outer_width+"px;height:"+this.outer_height+"px;overflow:hidden;z-index:2147483649;";if("left"==this.slidePos||"right"==this.slidePos)this.outerDiv.style.cssText=h()?"position:absolute;top:"+(c.getScrollTop()+c.getClientHeight()-this.verticalPos-this.outer_height)+"px;"+this.slidePos+":-"+(this.outer_width-this.slideDivWidth)+"px;"+b:"position:fixed;bottom:"+this.verticalPos+"px; "+this.slidePos+":-"+(this.outer_width-
this.slideDivWidth)+"px;"+b;else if("bottom"==this.slidePos||"top"==this.slidePos)if(h())if("middle"==this.slideBottomPos){if("bottom"==this.slidePos)var e=c.getScrollTop()+c.getClientHeight()-this.verticalPos-this.slideDivHeight-this.slideInfo.total-this.slideInfo.move;else"top"==this.slidePos&&(e=c.getScrollTop()-this.verticalPos-this.outer_height+this.slideDivHeight+this.slideInfo.total+this.slideInfo.move);this.outerDiv.style.cssText="position:absolute;top:"+e+"px;left:"+(c.getClientWidth()-this.outer_width)/
2+"px;"+b}else"left"==this.slideBottomPos?("bottom"==this.slidePos?e=c.getScrollTop()+c.getClientHeight()-this.verticalPos-this.slideDivHeight-this.slideInfo.total-this.slideInfo.move:"top"==this.slidePos&&(e=c.getScrollTop()-this.verticalPos-this.outer_height+this.slideDivHeight+this.slideInfo.total+this.slideInfo.move),this.outerDiv.style.cssText="position:absolute;top:"+e+"px;left:-"+this.iframeBorderShadowSize+"px;"+b):"right"==this.slideBottomPos&&("bottom"==this.slidePos?e=c.getScrollTop()+
c.getClientHeight()-this.verticalPos-this.slideDivHeight-this.slideInfo.total-this.slideInfo.move:"top"==this.slidePos&&(e=c.getScrollTop()-this.verticalPos-this.outer_height+this.slideDivHeight+this.slideInfo.total+this.slideInfo.move),this.outerDiv.style.cssText="position:absolute;top:"+e+"px;right:-"+this.iframeBorderShadowSize+"px;"+b);else"middle"==this.slideBottomPos?this.outerDiv.style.cssText="position:fixed;left:"+(c.getClientWidth()-this.outer_width)/2+"px;"+this.slidePos+":-"+(this.outer_height-
this.slideDivHeight)+"px;"+b:"left"==this.slideBottomPos?this.outerDiv.style.cssText="position:fixed;left:-"+this.iframeBorderShadowSize+"px; "+this.slidePos+":-"+(this.outer_height-this.slideDivHeight)+"px;"+b:"right"==this.slideBottomPos&&(this.outerDiv.style.cssText="position:fixed;right:-"+this.iframeBorderShadowSize+"px;"+this.slidePos+":-"+(this.outer_height-this.slideDivHeight)+"px;"+b);this.outerDiv.setAttribute("id","slideout"+this.slide_cpro_id);this.iframeDiv=document.createElement("div");
e="#7c7c7c 0px 0px "+this.iframeBorderShadowSize+"px "+this.iframeBorderSpreadSize+"px";b="width:"+this.slideWidth+"px;height:"+this.slideHeight+"px;border:"+this.iframeDivBorderWidth+"px solid "+this.iframeDivBorderColor+";background-color:#fff;";"left"==this.slidePos?this.iframeDiv.style.cssText="left:0px;top:0px;position:absolute;"+b:"right"==this.slidePos?this.iframeDiv.style.cssText="position:absolute;left:"+this.slideDivWidth+"px;top:0px;"+b:"bottom"==this.slidePos?this.iframeDiv.style.cssText=
"left:"+this.iframeBorderShadowSize+"px;top:"+this.slideDivHeight+"px;position:absolute;"+b+"box-shadow:"+e+";-webkit-box-shadow:"+e+";":"top"==this.slidePos&&(this.iframeDiv.style.cssText="left:"+this.iframeBorderShadowSize+"px;top:0px;position:absolute;"+b+"box-shadow:"+e+";-webkit-box-shadow:"+e+";");this.dialog=document.createElement("iframe");this.dialog.style.cssText="width:"+this.slideWidth+"px;height:"+this.slideHeight+"px;";this.dialog.setAttribute("scrolling","no");this.dialog.setAttribute("frameBorder",
"0");this.dialog.setAttribute("allowTransparency","true");this.dialog.setAttribute("align","center,center");this.iframeDiv.appendChild(this.dialog);this.barDivA=document.createElement("a");this.barDivA.style.cssText="cursor:pointer;text-decoration:none;";this.barDivA.setAttribute("href","javascript:void(0);");this.barDivA.onclick=this.slidebarBtnClick;e="height:"+this.slideDivHeight+"px;width:"+this.slideDivWidth+"px;background-color:"+this.slideDivBgColor+";";b="height:"+this.slideDivBtnBgSize+"px;width:"+
this.slideDivBtnBgSize+"px;";a="color:#fff;font-size:"+(this.slideBarTitleFontSize-1)+"px;font-family:microsoft yahei;font-weight:bold;";"left"==this.slidePos?(this.barDiv=document.createElement("div"),this.barDiv.style.cssText="position:absolute;"+e+"left:"+(this.outer_width-this.slideDivWidth)+"px;top:0px;-moz-border-radius:0px 5px 5px 0px;-webkit-border-radius:0px 5px 5px 0px;border-radius:0px 5px 5px 0px;",this.barBtnDiv=document.createElement("div"),this.barBtnDiv.style.cssText="position:absolute;left:"+
(this.slideDivWidth-this.slideDivBtnBgSize)/2+"px;top:"+(this.slideDivWidth-this.slideDivBtnBgSize)/2+"px;"+b+"background:url("+u+") no-repeat center center;",this.slideIsBarTitle&&(this.barTitle=document.createElement("div"),this.barTitle.style.cssText="position:absolute;height:"+(this.slideDivHeight-this.slideDivWidth)+"px;width:"+this.slideDivWidth+"px;left:0;top:"+(this.slideDivWidth-this.specSize)+"px;text-align:center;"+a+"line-height:"+this.slideBarTitleFontSize+"px",this.barTitle.innerHTML=
"\u4e3a<br>\u60a8<br>\u63a8<br>\u8350")):"right"==this.slidePos?(this.barDiv=document.createElement("div"),this.barDiv.style.cssText="position:absolute;"+e+"left:0px;top:0px;-moz-border-radius:5px 0px 0px 5px;-webkit-border-radius:5px 0px 0px 5px;border-radius:5px 0px 0px 5px;",this.barBtnDiv=document.createElement("div"),this.barBtnDiv.style.cssText="position:absolute;left:"+(this.slideDivWidth-this.slideDivBtnBgSize)/2+"px;top:"+(this.slideDivWidth-this.slideDivBtnBgSize)/2+"px;"+b+"background:url("+
w+") no-repeat center center;",this.slideIsBarTitle&&(this.barTitle=document.createElement("div"),this.barTitle.style.cssText="position:absolute;height:"+(this.slideDivHeight-this.slideDivWidth)+"px;width:"+this.slideDivWidth+"px;left:0;top:"+(this.slideDivWidth-this.specSize)+"px;text-align:center;"+a+"line-height:"+this.slideBarTitleFontSize+"px",this.barTitle.innerHTML="\u4e3a<br>\u60a8<br>\u63a8<br>\u8350")):"bottom"==this.slidePos?(this.barDiv=document.createElement("div"),this.barDiv.style.cssText=
"position:absolute;"+e+"right:"+this.iframeBorderShadowSize+"px;top:0px;-moz-border-radius:5px 5px 0px 0px;-webkit-border-radius:5px 5px 0px 0px;border-radius:5px 5px 0px 0px;",this.barBtnDiv=document.createElement("div"),this.barBtnDiv.style.cssText="position:absolute;right:"+(this.slideDivHeight-this.slideDivBtnBgSize)/2+"px;top:"+(this.slideDivHeight-this.slideDivBtnBgSize)/2+"px;"+b+"background:url("+s+") no-repeat center center;",this.slideIsBarTitle&&(this.barTitle=document.createElement("div"),
this.barTitle.style.cssText="position:absolute;height:"+this.slideDivHeight+"px;width:"+(this.slideDivWidth-this.slideDivHeight)+"px;right:"+(this.slideDivHeight-this.specSize)+"px;top:0;text-align:right;"+a+"line-height:"+this.slideDivHeight+"px",this.barTitle.innerHTML="\u4e3a\u60a8\u63a8\u8350")):"top"==this.slidePos&&(this.barDiv=document.createElement("div"),this.barDiv.style.cssText="position:absolute;"+e+"right:"+this.iframeBorderShadowSize+"px;top:"+(this.outer_height-this.slideDivHeight)+
"px;-moz-border-radius:0px 0px 5px 5px;-webkit-border-radius:0px 0px 5px 5px;border-radius:0px 0px 5px 5px;",this.barBtnDiv=document.createElement("div"),this.barBtnDiv.style.cssText="position:absolute;right:"+(this.slideDivHeight-this.slideDivBtnBgSize)/2+"px;top:"+(this.slideDivHeight-this.slideDivBtnBgSize)/2+"px;"+b+"background:url("+t+") no-repeat center center;",this.slideIsBarTitle&&(this.barTitle=document.createElement("div"),this.barTitle.style.cssText="position:absolute;height:"+this.slideDivHeight+
"px;width:"+(this.slideDivWidth-this.slideDivHeight)+"px;right:"+(this.slideDivHeight-this.specSize)+"px;top:0;text-align:right;"+a+"line-height:"+this.slideDivHeight+"px;",this.barTitle.innerHTML="\u4e3a\u60a8\u63a8\u8350"));this.barDiv.appendChild(this.barBtnDiv);this.slideIsBarTitle&&this.barDiv.appendChild(this.barTitle);this.barDivA.appendChild(this.barDiv);this.outerDiv.appendChild(this.iframeDiv);this.outerDiv.appendChild(this.barDivA);document.body.appendChild(this.outerDiv)}}};this.getUrl=
function(){return b.slideUrl};this.slidebarBtnClick=function(){b.slideInfo.enable=!1;0==b.slideInfo.move?b.slidein():(b.setUrl(),b.slideout());return!1};this.slideout=function(){b.slideTimer&&clearTimeout(b.slideTimer);b._slideout()};this._slideout=function(){0>b.slideInfo.move?(b.slideInfo.move+=b.slideInfo.interval,0<b.slideInfo.move&&(b.slideInfo.move=0),"right"==b.slidePos?b.outerDiv.style.right=b.slideInfo.move+"px":"left"==b.slidePos?b.outerDiv.style.left=b.slideInfo.move+"px":"bottom"==b.slidePos?
h()?b.outerDiv.style.top=c.getScrollTop()+c.getClientHeight()-b.verticalPos-b.slideDivHeight-b.slideInfo.total-b.slideInfo.move+"px":b.outerDiv.style.bottom=b.slideInfo.move+"px":"top"==b.slidePos&&(b.outerDiv.style.top=h()?c.getScrollTop()-b.verticalPos-b.outer_height+b.slideDivHeight+b.slideInfo.total+b.slideInfo.move+"px":b.slideInfo.move+"px"),b.slideTimer=setTimeout(b._slideout,b.slideInfo.speed)):"right"==b.slidePos?b.barBtnDiv.style.background="url("+u+") no-repeat center center":"left"==b.slidePos?
b.barBtnDiv.style.background="url("+w+") no-repeat center center":"bottom"==b.slidePos?b.barBtnDiv.style.background="url("+t+") no-repeat center center":"top"==b.slidePos&&(b.barBtnDiv.style.background="url("+s+") no-repeat center center")};this.slidein=function(){b.slideTimer&&clearTimeout(b.slideTimer);b._slidein()};this._slidein=function(){b.slideInfo.move>-b.slideInfo.total?(b.slideInfo.move-=b.slideInfo.interval,b.slideInfo.move<-b.slideInfo.total&&(b.slideInfo.move=-b.slideInfo.total),"right"==
b.slidePos?b.outerDiv.style.right=b.slideInfo.move+"px":"left"==b.slidePos?b.outerDiv.style.left=b.slideInfo.move+"px":"bottom"==b.slidePos?h()?b.outerDiv.style.top=c.getScrollTop()+c.getClientHeight()-b.verticalPos-b.slideDivHeight-b.slideInfo.total-b.slideInfo.move+"px":b.outerDiv.style.bottom=b.slideInfo.move+"px":"top"==b.slidePos&&(b.outerDiv.style.top=h()?c.getScrollTop()-b.verticalPos-b.outer_height+b.slideDivHeight+b.slideInfo.total+b.slideInfo.move+"px":b.slideInfo.move+"px"),b.slideTimer=
setTimeout(b._slidein,b.slideInfo.speed)):"right"==b.slidePos?b.barBtnDiv.style.background="url("+w+") no-repeat center center":"left"==b.slidePos?b.barBtnDiv.style.background="url("+u+") no-repeat center center":"bottom"==b.slidePos?b.barBtnDiv.style.background="url("+s+") no-repeat center center":"top"==b.slidePos&&(b.barBtnDiv.style.background="url("+t+") no-repeat center center")}}function q(){this.slideType=2;this.SLIDE_CLASSIC_TYPE=1;this.SLIDE_ABSOLUTE_TYPE=2;this.SLIDE_FIXED_TYPE=3;this.doms=
{container:null,containerParent:null,icon:null,content:null,title:null,iframeWrap:null,iframe:null};this.ANIM_TIME=30;this.ICON_CLOSE_URL="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/icon-lu-close.png";this.ICON_GOOD_URL="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/icon-lu-good.png";this.ICON_LIST_URL="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/icon-lu-list.png";this.ICON_PLUS_URL="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/icon-lu-plus.png";this.ICON_STAR_URL=
"http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/icon-lu-star.png";this.ICON_RECO_URL="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/icon-lu-reco.png";this.iframeWidth=300;this.iframeHeight=75;this.iframeWrapHeight=this.iframeWrapWidth=0;this.iframeWrapPadding=8;this.containerHeight=this.containerWidth=this.containerCorner=this.containerPosBottom=this.containerPosTop=this.containerPosRight=this.containerPosLeft=0;this.titleHeight=30;this.contentHeight=this.contentWidth=0;this.contentBorder=
1;this.iconHeight=this.iconWidth=32;this.iconType=1;var d=window.screen.availHeight||window.screen.height;this.MAX_LENGTH_AXIS_X=(window.screen.availWidth||window.screen.width)-this.iconWidth-30;this.MAX_LENGTH_AXIS_Y=d-this.iconHeight-30-100;this.POS_ERROR_CODE_UN="undefined";this.POS_ERROR_CODE_OVER="over";this.POS_ABS_ERROR_CODE_UN="error";this.curIconUrl=this.ICON_STAR_URL;this.isExpand=!1;this.iframeUrl="";this.supportTrans=this.supportFixed=this.setIframeDone=!1;this.logInfo={};var a=this;this.ieDeltaRight=
this.ieDeltaBottom=this.ieDeltaLeft=this.ieDeltaTop=-1;this.init=function(c){this.slideType=c.cpro_slide_type;this.logInfo=e(c);a.iconType=parseInt(c.cpro_icon_type)||1;a.supportTrans=a.checkSupportTransition();a.supportFixed=b();var d=a.initDOM(c);if(a.slideType==a.SLIDE_ABSOLUTE_TYPE&&!d)return!1;a.iframeUrl=f(c);a.bindEvent();n("Slide2",{tu:a.logInfo.tu,stid:a.logInfo.stid,sid:a.logInfo.sid,domain:a.logInfo.domain,type:1,random:+new Date});a.slideType==a.SLIDE_FIXED_TYPE&&!a.supportFixed&&a.fixedHack4IE()};
this.fixedHack4IE=function(){function b(){var a=c.getScrollTop(),l=c.getScrollLeft();0==d.containerCorner?-1==d.ieDeltaLeft?(d.doms.container.style.top=d.containerPosTop+a+"px",d.doms.container.style.left=d.containerPosLeft+l+"px"):(d.doms.container.style.top=d.ieDeltaTop+a+"px",d.doms.container.style.left=d.ieDeltaLeft+l+"px"):1==d.containerCorner?-1==d.ieDeltaRight?(d.doms.container.style.top=d.containerPosTop+a+"px",d.doms.container.style.right=d.containerPosRight-l+"px"):(d.doms.container.style.top=
d.ieDeltaTop+a+"px",d.doms.container.style.right=d.ieDeltaRight-l+"px"):2==d.containerCorner?e?(d.doms.container.style.display="none",d.doms.container.style.display="block"):-1==d.ieDeltaRight?(d.doms.container.style.right=d.containerPosRight-l+"px",d.doms.container.style.bottom=d.containerPosBottom-a+"px"):(d.doms.container.style.right=d.ieDeltaRight-l+"px",d.doms.container.style.bottom=d.ieDeltaBottom-a+"px"):3==d.containerCorner&&(e?(d.doms.container.style.display="none",d.doms.container.style.display=
"block"):-1==d.ieDeltaLeft?(d.doms.container.style.bottom=d.containerPosBottom-a+"px",d.doms.container.style.left=d.containerPosLeft+l+"px"):(d.doms.container.style.bottom=d.ieDeltaBottom-a+"px",d.doms.container.style.left=d.ieDeltaLeft+l+"px"))}var d=a,e=h();b();i.bind(window,"scroll",function(){b()});i.bind(window,"resize",function(){b()})};this.setIframeUrl=function(){a.doms.iframe.setAttribute("src",a.iframeUrl);a.setIframeDone=!0};this.generateTransition=function(a){for(var c=["","moz","webkit",
"ms","o"],b="",a=a/1E3,d=0;d<c.length;d++)b+=c[d]?"-"+c[d]+"-":"transition: all "+a+"s;";return b};this.expandAdHandler=function(){a.setIframeDone||a.setIframeUrl();a.extendAd();a.flipIcon();a.isExpand=!0};this.collapseAdHandler=function(){a.collapseForAll();a.flipIcon(!0);a.isExpand=!1;n("Slide2",{tu:a.logInfo.tu,stid:a.logInfo.stid,sid:a.logInfo.sid,domain:a.logInfo.domain,type:0,random:+new Date})};this.bindEvent=function(){i.bind(a.doms.icon,"mouseover",function(){a.isExpand||a.expandAdHandler()});
i.bind(a.doms.icon,"click",function(){a.isExpand?a.collapseAdHandler():a.expandAdHandler()})};this.flipIcon=function(c){a.doms.icon.style.backgroundImage=c?"url("+a.generateIconUrl()+")":"url("+a.ICON_CLOSE_URL+")"};this.extendAd=function(){switch(a.checkAvailableSpace()){case 0:a.expandOnLeftTop();break;case 1:a.expandOnRightTop();break;case 2:a.expandOnRightBottom();break;case 3:a.expandOnLeftBottom();break;default:a.expandOnRightBottom()}};this.generateIconUrl=function(){var c="";switch(a.iconType){case 1:c=
a.ICON_GOOD_URL;break;case 2:c=a.ICON_LIST_URL;break;case 3:c=a.ICON_PLUS_URL;break;case 4:c=a.ICON_RECO_URL;break;case 5:c=a.ICON_STAR_URL;break;default:c=a.ICON_GOOD_URL}return c};this.parsePositionParam=function(c){return void 0==c?a.POS_ERROR_CODE_UN:parseInt(c)};this.checkBeyoundMax=function(c,b){return b?c>b?a.POS_ERROR_CODE_OVER:c:c};this.initDOM=function(b){a.iframeWidth=parseInt(b.rsi0);a.iframeHeight=parseInt(b.rsi1);a.iframeWrapHeight=a.iframeHeight;a.iframeWrapWidth=a.iframeWidth;a.contentWidth=
a.iframeWrapWidth+2*a.iframeWrapPadding;a.contentHeight=a.iframeWrapHeight+2*a.iframeWrapPadding+a.titleHeight;a.containerWidth=a.iconWidth+10+a.contentWidth+2*a.contentBorder;a.containerHeight=a.contentHeight+2*a.contentBorder;a.containerPosLeft=a.parsePositionParam(b.cpro_pos_left);a.containerPosRight=a.parsePositionParam(b.cpro_pos_right);a.containerPosTop=a.parsePositionParam(b.cpro_pos_top);a.containerPosBottom=a.parsePositionParam(b.cpro_pos_bottom);a.slideType==a.SLIDE_FIXED_TYPE&&(a.containerPosLeft=
a.checkBeyoundMax(a.containerPosLeft,a.MAX_LENGTH_AXIS_X),a.containerPosRight=a.checkBeyoundMax(a.containerPosRight,a.MAX_LENGTH_AXIS_X),a.containerPosLeft==a.POS_ERROR_CODE_OVER?a.containerPosRight=10:a.containerPosRight==a.POS_ERROR_CODE_OVER&&(a.containerPosLeft=10),a.containerPosTop=a.checkBeyoundMax(a.containerPosTop,a.MAX_LENGTH_AXIS_Y),a.containerPosBottom=a.checkBeyoundMax(a.containerPosBottom,a.MAX_LENGTH_AXIS_Y),a.containerPosTop==a.POS_ERROR_CODE_OVER?a.containerPosBottom=10:a.containerPosBottom==
a.POS_ERROR_CODE_OVER&&(a.containerPosTop=10));a.containerPosLeft==a.POS_ERROR_CODE_UN&&a.containerPosRight==a.POS_ERROR_CODE_UN&&(a.containerPosLeft=10);a.containerPosTop==a.POS_ERROR_CODE_UN&&a.containerPosBottom==a.POS_ERROR_CODE_UN&&(a.containerPosTop=10);var d="absolute";a.slideType==a.SLIDE_ABSOLUTE_TYPE?d="absolute;":a.slideType==a.SLIDE_FIXED_TYPE&&(d=a.supportFixed?"fixed;":"absolute;");var e="";a.containerPosLeft!=a.POS_ERROR_CODE_UN&&a.containerPosLeft!=a.POS_ERROR_CODE_OVER?e+="left:"+
a.containerPosLeft+"px;":a.containerPosRight!=a.POS_ERROR_CODE_UN&&a.containerPosRight!=a.POS_ERROR_CODE_OVER&&(e+="right:"+a.containerPosRight+"px;");a.containerPosTop!=a.POS_ERROR_CODE_UN&&a.containerPosTop!=a.POS_ERROR_CODE_OVER?e+="top:"+a.containerPosTop+"px;":a.containerPosBottom!=a.POS_ERROR_CODE_UN&&a.containerPosBottom!=a.POS_ERROR_CODE_OVER&&(e+="bottom:"+a.containerPosBottom+"px;");-1<e.indexOf("left")&&-1<e.indexOf("top")?a.containerCorner=0:-1<e.indexOf("right")&&-1<e.indexOf("top")?
a.containerCorner=1:-1<e.indexOf("right")&&-1<e.indexOf("bottom")?a.containerCorner=2:-1<e.indexOf("left")&&-1<e.indexOf("bottom")&&(a.containerCorner=3);d="position:"+d+e+"width: "+a.iconWidth+"px;height: "+a.iconHeight+"px;overflow: hidden;z-index: 2147483647;"+a.generateTransition(500);b="SLIDE_SLOT_"+b.cpro_id;document.write('<div id="'+b+'" style="'+d+'"></div>');a.doms.container=document.getElementById(b);3==this.slideType&&(c.browser.ie&&7>=c.browser.ie?setTimeout(function(){document.body.appendChild(a.doms.container)},
1E3):document.body.appendChild(a.doms.container));a.doms.icon=document.createElement("div");a.doms.icon.style.cssText="width:"+a.iconWidth+"px;height:"+a.iconHeight+"px;position:absolute;background:url("+a.generateIconUrl()+");right: 0;top: 0;cursor:pointer;";a.doms.content=document.createElement("div");a.doms.content.style.cssText="height: "+a.contentHeight+"px;width: "+a.contentWidth+"px;left: "+a.iconWidth+10+"px;top: 0;border: 1px solid #C5C5C5;position:absolute;overflow:hidden;";a.doms.title=
document.createElement("div");a.doms.title.style.cssText="height:"+a.titleHeight+"px;background: #0F6BD8;line-height: "+a.titleHeight+"px;text-align: center;font-size: 16px;color: white;";a.doms.title.innerHTML="\u4e3a\u60a8\u63a8\u8350";a.doms.iframeWrap=document.createElement("div");a.doms.iframeWrap.style.cssText="padding: "+a.iframeWrapPadding+"px;height: "+a.iframeWrapHeight+"px;width: "+a.iframeWrapWidth+"px;background: white;";a.doms.iframe=document.createElement("iframe");a.doms.iframe.style.width=
a.iframeWidth+"px";a.doms.iframe.style.height=a.iframeHeight+"px";a.doms.iframe.setAttribute("scrolling","no");a.doms.iframe.setAttribute("frameBorder","0");a.doms.iframe.setAttribute("allowTransparency","true");a.doms.iframe.setAttribute("align","center,center");a.doms.container.appendChild(a.doms.icon);a.doms.container.appendChild(a.doms.content);a.doms.content.appendChild(a.doms.title);a.doms.content.appendChild(a.doms.iframeWrap);a.doms.iframeWrap.appendChild(a.doms.iframe);return a.slideType==
a.SLIDE_ABSOLUTE_TYPE&&(a.doms.containerParent=a.doms.container.parentNode,d=a.getStyle(a.doms.containerParent).position,!d||"static"==d||!a.supportFixed&&"fixed"==d)?(a.doms.containerParent.removeChild(a.doms.container),!1):!0};this.checkSupportTransition=function(){for(var a=document.createElement("div"),c=["ms","webkit","moz","o",""],b="",d=0;d<c.length;d++)b+=(c[d]?"-"+c[d]+"-":"")+"transition: all .5s;";a.style.cssText=b;for(d=0;d<c.length;d++)if(a.style[c[d]+"TransitionDuration"]||a.style[c[d].charAt(0).toUpperCase()+
c[d].slice(1)+"TransitionDuration"])return!0;return!1};this.resetPosition=function(a){a.style.top="";a.style.left="";a.style.right="";a.style.bottom=""};this.collapseForAll=function(){if(a.supportTrans)switch(a.doms.container.style.width=a.iconWidth+"px",a.doms.container.style.height=a.iconHeight+"px",a.containerCorner){case 0:a.doms.container.style.top=a.containerPosTop+"px";a.doms.container.style.left=a.containerPosLeft+"px";break;case 1:a.doms.container.style.top=a.containerPosTop+"px";a.doms.container.style.right=
a.containerPosRight+"px";break;case 2:a.doms.container.style.right=a.containerPosRight+"px";a.doms.container.style.bottom=a.containerPosBottom+"px";break;case 3:a.doms.container.style.left=a.containerPosLeft+"px",a.doms.container.style.bottom=a.containerPosBottom+"px"}else switch(a.containerCorner){case 0:a.animate(a.doms.container,a.iconWidth,a.iconHeight,a.containerPosTop,a.containerPosLeft,null,null);break;case 1:a.animate(a.doms.container,a.iconWidth,a.iconHeight,a.containerPosTop,null,null,a.containerPosRight);
break;case 2:a.animate(a.doms.container,a.iconWidth,a.iconHeight,null,null,a.containerPosBottom,a.containerPosRight);break;case 3:a.animate(a.doms.container,a.iconWidth,a.iconHeight,null,a.containerPosLeft,a.containerPosBottom,null)}};this.animate=function(b,d,e,f,g,k,i){var j=h(),b=b||a.doms.container,v=a.ANIM_TIME,m,q,o=parseInt(b.style.width),p=parseInt(b.style.height),n=parseInt(b.style.top)||0,r=parseInt(b.style.left)||0,y=parseInt(b.style.bottom)||0,z=parseInt(b.style.right)||0;a.slideType==
a.SLIDE_FIXED_TYPE&&!a.supportFixed&&(m=c.getScrollTop(),q=c.getScrollLeft(),f=null==f?n:f+m,g=null==g?r:g+q,k=null==k?y:j?k:k-m,i=null==i?z:j?i:i-q,a.ieDeltaTop=f-m,a.ieDeltaLeft=g-q,a.ieDeltaBottom=k+m,a.ieDeltaRight=i+q);var u=(d-o)/v,w=(e-p)/v,s=null==f?0:(f-n)/v,t=null==g?0:(g-r)/v,B=null==i?0:(i-z)/v,C=null==k?0:(k-y)/v,x=!1,A=!1,D=t?!1:!0,E=s?!1:!0,F=B?!1:!0,G=C?!1:!0;setTimeout(function H(){o+=u;p+=w;s&&(n+=s);t&&(r+=t);B&&(z+=B);C&&(y+=C);0<u?o>=d?(b.style.width=d+"px",x=!0):b.style.width=
o+"px":o<=d?(x=!0,b.style.width=d+"px"):b.style.width=o+"px";0<w?p>=e?(A=!0,b.style.height=e+"px"):b.style.height=p+"px":p<=e?(A=!0,b.style.height=e+"px"):b.style.height=p+"px";0<s?n>=f?(E=!0,b.style.top=f+"px"):b.style.top=n+"px":0>s&&(n<=f?(E=!0,b.style.top=f+"px"):b.style.top=n+"px");0<t?r>=g?(D=!0,b.style.left=g+"px"):b.style.left=r+"px":0>t&&(r<=g?(D=!0,b.style.left=g+"px"):b.style.left=r+"px");0<B?z>=i?(F=!0,b.style.right=i+"px"):b.style.right=z+"px":0>B&&(z<=i?(F=!0,b.style.right=i+"px"):b.style.right=
z+"px");0<C?y>=k?(G=!0,b.style.bottom=k+"px"):b.style.bottom=y+"px":0>C&&(y<=k?(G=!0,b.style.bottom=k+"px"):b.style.bottom=y+"px");(!x||!A||!D||!E||!F||!G)&&setTimeout(function(){H()})})};this.getStyle=function(a){return window.getComputedStyle?window.getComputedStyle(a):a.currentStyle};this.checkAvailableSpace=function(){if(a.slideType==a.SLIDE_ABSOLUTE_TYPE){var b=a.getStyle(a.doms.containerParent),d=parseInt(b.width),e=parseInt(b.height),f=b=0,g=0,k=0;a.containerPosTop!=a.POS_ERROR_CODE_UN?(b=
a.containerPosTop,g=e-b-a.iconHeight):a.containerPosBottom!=a.POS_ERROR_CODE_UN&&(g=a.containerPosBottom,b=e-g-a.iconHeight);a.containerPosLeft!=a.POS_ERROR_CODE_UN?(f=a.containerPosLeft,k=d-f-a.iconWidth):a.containerPosRight!=a.POS_ERROR_CODE_UN&&(k=a.containerPosRight,f=d-k-a.iconWidth);b=[f*b,k*b,k*g,f*g];f=b[0];g=0;for(k=1;k<b.length;k++)b[k]>f&&(f=b[k],g=k);return g}if(a.slideType==a.SLIDE_FIXED_TYPE){var d=h(),e=window.innerWidth||("BackCompat"==document.compatMode?document.body.clientWidth:
document.documentElement.clientWidth),i=window.innerHeight||("BackCompat"==document.compatMode?document.body.clientHeight:document.documentElement.clientHeight),b=parseInt(a.doms.container.style.top,10)||0,g=parseInt(a.doms.container.style.bottom,10)||0,f=parseInt(a.doms.container.style.left,10)||0,k=parseInt(a.doms.container.style.right,10)||0,j,v;a.supportFixed||(j=c.getScrollLeft(),v=c.getScrollTop(),b=b?b-v:0,f=f?f-j:0,g=g?d?g:g+v:0,k=k?d?k:k+j:0);if(0==b&&0==g){if(0==a.containerCorner||1==a.containerCorner)b=
0,g=i-b-a.iconHeight;if(2==a.containerCorner||3==a.containerCorner)g=0,b=i-g-a.iconHeight}else b?g||(g=i-b-a.iconHeight):b=i-g-a.iconHeight;if(0==f&&0==k){if(0==a.containerCorner||3==a.containerCorner)f=0,k=e-f-a.iconWidth;if(1==a.containerCorner||2==a.containerCorner)k=0,f=e-k-a.iconWidth}else f?k||(k=e-f-a.iconWidth):f=e-k-a.iconWidth;b=[f*b,k*b,k*g,f*g];f=b[0];g=0;for(k=1;k<b.length;k++)b[k]>f&&(f=b[k],g=k);return g}};this.expandOnRightBottom=function(){a.resetPosition(a.doms.icon);a.resetPosition(a.doms.content);
a.doms.icon.style.left=0;a.doms.icon.style.top=0;a.doms.content.style.left=a.iconWidth+10+"px";a.doms.content.style.top=0;var b=a.containerPosRight-(a.containerWidth-a.iconWidth),c=a.containerPosBottom-(a.containerHeight-a.iconHeight);a.supportTrans&&(a.doms.container.style.width=a.containerWidth+"px",a.doms.container.style.height=a.containerHeight+"px");0==a.containerCorner?a.supportTrans||a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,null,null):1==a.containerCorner?a.supportTrans?
a.doms.container.style.right=b+"px":a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,null,b):2==a.containerCorner?a.supportTrans?(a.doms.container.style.right=b+"px",a.doms.container.style.bottom=c+"px"):a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,c,b):3==a.containerCorner&&(a.supportTrans?a.doms.container.style.bottom=c+"px":a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,c,null))};this.expandOnRightTop=function(){a.resetPosition(a.doms.icon);
a.resetPosition(a.doms.content);a.doms.icon.style.left=0;a.doms.icon.style.bottom=0;a.doms.content.style.left=a.iconWidth+10+"px";a.doms.content.style.bottom=0;var b=a.containerPosTop-(a.containerHeight-a.iconHeight),c=a.containerPosRight-(a.containerWidth-a.iconWidth);a.supportTrans&&(a.doms.container.style.width=a.containerWidth+"px",a.doms.container.style.height=a.containerHeight+"px");0==a.containerCorner?a.supportTrans?a.doms.container.style.top=b+"px":a.animate(a.doms.container,a.containerWidth,
a.containerHeight,b,null,null,null):1==a.containerCorner?a.supportTrans?(a.doms.container.style.top=b+"px",a.doms.container.style.right=c+"px"):a.animate(a.doms.container,a.containerWidth,a.containerHeight,b,null,null,c):2==a.containerCorner?a.supportTrans?a.doms.container.style.right=c+"px":a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,null,c):3==a.containerCorner&&!a.supportTrans&&a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,null,null)};this.expandOnLeftTop=
function(){a.resetPosition(a.doms.icon);a.resetPosition(a.doms.content);a.doms.icon.style.right=0;a.doms.icon.style.bottom=0;a.doms.content.style.right=a.iconWidth+10+"px";a.doms.content.style.bottom=0;var b=a.containerPosTop-(a.containerHeight-a.iconHeight),c=a.containerPosLeft-(a.containerWidth-a.iconWidth);a.supportTrans&&(a.doms.container.style.width=a.containerWidth+"px",a.doms.container.style.height=a.containerHeight+"px");0==a.containerCorner?a.supportTrans?(a.doms.container.style.top=b+"px",
a.doms.container.style.left=c+"px"):a.animate(a.doms.container,a.containerWidth,a.containerHeight,b,c,null,null):1==a.containerCorner?a.supportTrans?a.doms.container.style.top=b+"px":a.animate(a.doms.container,a.containerWidth,a.containerHeight,b,null,null,null):2==a.containerCorner?a.supportTrans||a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,null,null):3==a.containerCorner&&(a.supportTrans?a.doms.container.style.left=c+"px":a.animate(a.doms.container,a.containerWidth,a.containerHeight,
null,c,null,null))};this.expandOnLeftBottom=function(){a.resetPosition(a.doms.icon);a.resetPosition(a.doms.content);a.doms.icon.style.right=0;a.doms.icon.style.top=0;a.doms.content.style.right=a.iconWidth+10+"px";a.doms.content.style.top=0;var b=a.containerPosLeft-(a.containerWidth-a.iconWidth),c=a.containerPosBottom-(a.containerHeight-a.iconHeight);a.supportTrans&&(a.doms.container.style.width=a.containerWidth+"px",a.doms.container.style.height=a.containerHeight+"px");0==a.containerCorner?a.supportTrans?
a.doms.container.style.left=b+"px":a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,b,null,null):1==a.containerCorner?a.supportTrans||a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,null,null):2==a.containerCorner?a.supportTrans?a.doms.container.style.bottom=c+"px":a.animate(a.doms.container,a.containerWidth,a.containerHeight,null,null,c,null):3==a.containerCorner&&(a.supportTrans?(a.doms.container.style.bottom=c+"px",a.doms.container.style.left=b+"px"):a.animate(a.doms.container,
a.containerWidth,a.containerHeight,null,b,c,null))}}function x(){this.doms={container:null,logo:null,layoutWrap:null,iframeWrap:null,iframe:null,btnWrap:null,btnIcon:null};this.adIsExpand=!0;this.adHeight=40;this.adZindex=2147483647;this.adColor="#2C85FF";this.logoWidth=30;this.logoHeight=this.adHeight;this.logoBgColor=this.adColor;this.logoBgSrc="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/slide-logo_blue.png";this.btnWrapWidth=10;this.btnWrapWhenShrinkBgColor=this.adColor;this.btnWrapWhenExpandBgColor=
"#D5D5D5";this.btnIconBgWhenShrink="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/slide-arrow-right.jpg";this.btnIconBgWhenExpand="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/slide-arrow-left.jpg";this.logInfo={};this.init=function(b){this.slideType=b.cpro_slide_type;this.initDOM(b);this.bindEvent();this.logInfo=e(b,{stid:43});n("Slide",{tu:this.logInfo.tu,stid:this.logInfo.stid,sid:this.logInfo.sid,domain:this.logInfo.domain,type:1,random:+new Date})};this.bindEvent=function(){var b=
this,a=h();this.doms.btnWrap.onclick=function(){b.adIsExpand?(b.adIsExpand=!1,b.doms.container.style.width="41px",b.doms.btnWrap.style.background=b.btnWrapWhenShrinkBgColor,b.doms.btnWrap.style.borderLeft="1px solid rgb(192,192,192)",b.doms.btnIcon.style.background='no-repeat url("'+b.btnIconBgWhenShrink+'")',b.doms.btnIcon.style.right="-1px",a&&(b.doms.logo.style.display="none",setTimeout(function(){b.doms.logo.style.display="block"},0)),n("Slide2",{tu:b.logInfo.tu,stid:b.logInfo.stid,sid:b.logInfo.sid,
domain:b.logInfo.domain,type:0,random:+new Date})):(b.adIsExpand=!0,b.doms.container.style.width="100%",b.doms.btnWrap.style.background=b.btnWrapWhenExpandBgColor,b.doms.btnWrap.style.borderLeft="none",b.doms.btnIcon.style.background='no-repeat url("'+b.btnIconBgWhenExpand+'")',b.doms.btnIcon.style.right="3px")}};this.fixedHack4IE=function(){function b(){var e=c.getScrollTop(),f=c.getScrollLeft();d?(a.doms.container.style.display="none",a.doms.container.style.display="block"):(a.doms.container.style.bottom=
0-e+"px",a.doms.container.style.left=0+f+"px")}var a=this,d=h();i.bind(window,"scroll",function(){b()});i.bind(window,"resize",function(){b()})};this.initDOM=function(c){var a=b();this.doms.container=document.createElement("div");this.doms.container.style.cssText="width: 100%;height: "+this.adHeight+"px;position:"+(a?"fixed":"absolute")+";bottom: 0;left: 0;";this.doms.layoutWrap=document.createElement("div");this.doms.layoutWrap.style.cssText="width:100%;height:"+this.adHeight+"px;float:left";this.doms.iframeWrap=
document.createElement("div");this.doms.iframeWrap.style.cssText="margin: 0 "+this.btnWrapWidth+"px 0 "+this.logoWidth+"px;height:"+this.adHeight+"px;";this.doms.iframe=document.createElement("iframe");this.doms.iframe.style.width="100%";this.doms.iframe.style.height=this.adHeight+"px";this.doms.iframe.setAttribute("scrolling","no");this.doms.iframe.setAttribute("frameBorder","0");this.doms.iframe.setAttribute("allowTransparency","true");this.doms.iframe.setAttribute("align","center,center");this.doms.iframe.setAttribute("src",
f(c));this.doms.logo=document.createElement("div");this.doms.logo.style.cssText="width:"+this.logoWidth+"px;height:"+this.logoHeight+'px;float:left;margin-left: -100%;background: url("'+this.logoBgSrc+'") ';this.doms.btnWrap=document.createElement("div");this.doms.btnWrap.style.cssText="width:"+this.btnWrapWidth+"px;height:"+this.adHeight+"px;float:left;position:relative;margin-left: "+-1*(this.btnWrapWidth+1)+"px;background: "+this.btnWrapWhenExpandBgColor+";overflow:hidden;cursor:pointer;";this.doms.btnIcon=
document.createElement("div");this.doms.btnIcon.style.cssText='width:8px;height:8px;position:absolute;top:17px;right:3px;background: no-repeat url("'+this.btnIconBgWhenExpand+'")';this.doms.container.appendChild(this.doms.layoutWrap);this.doms.layoutWrap.appendChild(this.doms.iframeWrap);this.doms.iframeWrap.appendChild(this.doms.iframe);this.doms.container.appendChild(this.doms.logo);this.doms.container.appendChild(this.doms.btnWrap);this.doms.btnWrap.appendChild(this.doms.btnIcon);document.body.appendChild(this.doms.container);
a||this.fixedHack4IE()}}var w="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/left.png",u="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/right.png",s="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/up.png",t="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/down.png",A=function(){var b=c.getScrollTop()+c.getClientHeight()-c.getScrollHeight();if("BackCompat"==document.compatMode)var b=document.body.clientHeight,a=document.body.scrollHeight,d=document.body.scrollTop;else b=
document.documentElement.clientHeight,a=document.documentElement.scrollHeight,d=0==document.documentElement.scrollTop?document.body.scrollTop:document.documentElement.scrollTop;var b=(d+b)/a,e;for(e in m)h()&&m[e].resetBottomLoc(),m[e].isSlideEnable()&&(b>m[e].slidePercent&&b<=m[e].slideEndPercent?(m[e].setUrl(),m[e].slideout()):m[e].slidein())},m=m||{},p=!1;return{render:function(b,a){function d(){var a=f;void 0!=a.cpro_slideLU_abs_pos||void 0!=a.slideLU_abs_pos?(a.pos=a.cpro_slideLU_abs_pos||a.slideLU_abs_pos,
a.cpro_slideLU_abs_pos=a.cpro_slideLU_abs_pos||a.slideLU_abs_pos):void 0!=a.pos?a.cpro_slideLU_abs_pos=a.pos:(a.cpro_slideLU_abs_pos="left",a.pos="left");void 0!=a.cpro_slideLU_rel_pos||void 0!=a.slideLU_rel_pos?"left"==a.cpro_slideLU_abs_pos||"right"==a.cpro_slideLU_abs_pos?(a.ver=a.cpro_slideLU_rel_pos||a.slideLU_rel_pos,a.cpro_slideLU_rel_pos=a.cpro_slideLU_rel_pos||a.slideLU_rel_pos,a.bpos="middle"):(a.ver="0",a.cpro_slideLU_rel_pos=a.cpro_slideLU_rel_pos||a.slideLU_rel_pos,a.bpos=a.cpro_slideLU_rel_pos):
(void 0!=a.ver?"left"==a.cpro_slideLU_abs_pos||"right"==a.cpro_slideLU_abs_pos?a.cpro_slideLU_rel_pos=a.ver:(a.ver="0",a.cpro_slideLU_rel_pos="middle"):void 0!=a.bpos?"left"==a.cpro_slideLU_abs_pos||"right"==a.cpro_slideLU_abs_pos?a.cpro_slideLU_rel_pos="50":(a.ver="0",a.cpro_slideLU_rel_pos="middle"):"left"==a.cpro_slideLU_abs_pos||"right"==a.cpro_slideLU_abs_pos?(a.ver="50",a.cpro_slideLU_rel_pos="50"):(a.ver="0",a.cpro_slideLU_rel_pos="middle"),a.bpos="middle");void 0!=a.cpro_slideLU_out_per||
void 0!=a.slideLU_out_per?(a.per=a.cpro_slideLU_out_per||a.slideLU_out_per,a.cpro_slideLU_out_per=a.cpro_slideLU_out_per||a.slideLU_out_per):void 0!=a.per?a.cpro_slideLU_out_per=a.per||a.slideLU_out_per:(a.cpro_slideLU_out_per="0.3",a.per="0.3");void 0!=a.cpro_slideLU_in_per||void 0!=a.slideLU_in_per?(a.per2=a.cpro_slideLU_in_per||a.slideLU_in_per,a.cpro_slideLU_in_per=a.cpro_slideLU_in_per||a.slideLU_in_per):void 0!=a.per2?a.cpro_slideLU_in_per=a.per2:(a.cpro_slideLU_in_per="1.0",a.per2="1.0");f=
a;f.curl=h.serviceUrl+h.paramString;m[e]=new o;m[e].init(f);"u0"===e.split("_")[0]&&(m[e].setUrl(),m[e].slideout());!p&&"u0"!=e.split("_")[0]&&(i.bind(window,"scroll",A),p=!0)}b.displayType="float-slide";var e=b.id,f=b._html;f.cpro_id=e;var h=g.processSlotData(b);f.curl=h.serviceUrl+h.paramString;f.cpro_slide_type=parseInt(f.cpro_slide_type);if(f.cpro_slide_type&&(2==f.cpro_slide_type||3==f.cpro_slide_type))return m[e]=new q,m[e].init(f),!0;if(f.cpro_slide_type&&4==f.cpro_slide_type)return m[e]=new x,
m[e].init(f),!0;var j=i.g(a);j&&j.parentNode&&j.parentNode.removeChild(j);c.browser.ie&&7>=c.browser.ie?setTimeout(function(){d()},1E3):d()}}});})();
